### PR TITLE
Add database status

### PR DESCRIPTION
**Pull request by Crevil**
This change adds custom columns with databases' reconcilation status' along with
the database name for easy kubectl'ing.

This is an example output for three resources. One with a bad config map
reference, second with an invalid database name and lastly a valid and
reconciled database.

    $ kubectl get postgresqldatabases.lunarway.com
    NAME                       DATABASE              STATUS    UPDATED
    product-bad-configmap-db   productbadconfigmap   Invalid   4m29s
    product-bad-name-db        product-bad-name      Failed    4m28s
    product-db                 product               Running   4m29s

### CODE REVIEW

**Comment by Crevil** [comment]
I'll see if I can add the actual status as well. So when `kubectl describe postgresqldatabase.lunarway.com` we can see what is invalid instead of reaching to the logs.

**Comment by Crevil** [comment]
I've added an `error` field to the `status` struct to pass on information about what went wrong.

Here is an example from describing the database with an invalid name.

```
$ kubectl describe postgresqldatabases.lunarway.com product-bad-name-db
Name:         product-bad-name-db
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"lunarway.com/v1alpha1","kind":"PostgreSQLDatabase","metadata":{"annotations":{},"name":"product-bad-name-db","namespace":"d...
API Version:  lunarway.com/v1alpha1
Kind:         PostgreSQLDatabase
Metadata:
  Creation Timestamp:  2019-12-18T16:54:44Z
  Generation:          1
  Resource Version:    18646
  Self Link:           /apis/lunarway.com/v1alpha1/namespaces/default/postgresqldatabases/product-bad-name-db
  UID:                 1b9236be-e199-40e8-b5ec-19236366f23d
Spec:
  Host:
    Value:  postgresql:5432
  Name:     product-bad-name
  Password:
    Value:  12345678
Status:
  Error:          create database product-bad-name on host postgresql://iam_creator:@postgresql:5432/postgres?sslmode=disable: create service user: pq: syntax error at or near "-"
  Phase:          Failed
  Phase Updated:  2019-12-18T16:57:28Z
Events:           <none>
```

**Comment by eXeDK** [comment]
Is this for creating databases where `phase` is then if the database is created correctly or not?

**Comment by Crevil** [comment]
Sort of yes. The status will indicate if there were some issue in the reconiliation of the database.
That could be wrong credentials, invalid names, unknown hosts etc.

I've not done anything nice on the errors yet, but it is rather trivial to communicate these information back in the status and error fields.

**Comment by eXeDK** [comment]
Got ya. The "phase" concept was not fully clear at first. Sounds good though.

**Comment by Crevil** [comment]
Yeah, it's kind of ugly but conventional for k8s.
As the main status struct is named `Status` with a field inside it named `Status` is not nice. JSON path `.status.status` for example.

**Pull request merged**
