### PR TITLE
Document user-roles and user-role-prefix flags in README

### PR DESCRIPTION
**Pull request by kaspernissen**

### CODE REVIEW

**Comment by Crevil** [comment]
This is not a requirement of the controller. It is however a requirement that the roles set in flag `--user-roles` are available when the controller starts, ie. it will not create these by it self.

**Comment by Crevil** [comment]
So maybe we should make that more clear in the documentation?

**Comment by kaspernissen** [comment]
Yes, that would make sense. Feel free to suggest a change.

**Comment by Crevil** [comment]
Actually that flag and functionality is not documented at all :( I'll give it a go on this branch.

**Comment by kaspernissen** [comment]
Sounds good 👍

**Comment by Crevil** [comment]
What do you think of this @kaspernissen ?

**Comment by kaspernissen** [comment]
That's a lot better. 👍

**Pull request merged**
